### ISSUE TITLE
Function to copy R data frame directly to clipboard

### ISSUE THREAD

**Issue by akellygithub** [departmentfortransport/R-cookbook#54]
Hi!

Something that i've stumbled across that would be useful to add:

Normally when you have a table in a data frame in R, if you want to get this into a spreadsheet you will need to use functions like `writexl::write_xlsx` or the base `write.csv` to do so. Wouldn’t it be easier to simply copy the entire data frame to the clipboard, so that you can paste it in the spreadsheet yourself? Well try this:

`write.table(df, "clipboard", sep="\t", col.names=TRUE)`

df =  data frame you want to copy 
col.names = if you want the column headers leave as TRUE. Just the data, change to FALSE

If you get warnings about “too big for clipboard”, you can even specify what size of clipboard you want to copy to, such as:

`write.table(df, "clipboard-16384", sep="\t", col.names=TRUE)`

This tells the write.table to copy df to a clipboard with size 2^14.

**Comment by h-bougdah** [comment]
Thanks Andrew, I've added this now! In the data import/export chapter.

**Comment by mmahmoudian** [comment]
I was looking for a way to to do the same exact thing but I get an error. I copied the what @akellygithub suggested and changed `df` with `iris` to test it:

```r
write.table(iris, "clipboard", sep="\t", col.names=TRUE)
```
and the output is:
> ```
> Error in file(file, ifelse(append, "a", "w")) :
> 'mode' for the clipboard must be 'r' on Unix
> ```

I managed to get it done through `clipr::write_clip()` though.
